-- MySQL Script generated by MySQL Workbench
-- Tue Nov  4 20:15:43 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema irkpo_events
-- -----------------------------------------------------
-- База данных на тему: "Разработка базы данных для системы организации мероприятий колледжа"

-- -----------------------------------------------------
-- Schema irkpo_events
--
-- База данных на тему: "Разработка базы данных для системы организации мероприятий колледжа"
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `irkpo_events` DEFAULT CHARACTER SET utf8mb4 ;
USE `irkpo_events` ;

-- -----------------------------------------------------
-- Table `irkpo_events`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`faculties` (
                                                          `facultyID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор отделения',
                                                          `facultyName` VARCHAR(100) NOT NULL COMMENT 'Наименование отделения',
    PRIMARY KEY (`facultyID`),
    UNIQUE INDEX `facultyName_UNIQUE` (`facultyName` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица отделений';


-- -----------------------------------------------------
-- Table `irkpo_events`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`groups` (
                                                       `groupID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор группы',
                                                       `groupName` VARCHAR(50) NOT NULL COMMENT 'Наименование группы',
    `faculties_facultyID` INT NULL COMMENT 'Связь отделения с группами',
    PRIMARY KEY (`groupID`),
    INDEX `fk_groups_faculties_idx` (`faculties_facultyID` ASC) VISIBLE,
    CONSTRAINT `fk_groups_faculties`
    FOREIGN KEY (`faculties_facultyID`)
    REFERENCES `irkpo_events`.`faculties` (`facultyID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица учебных групп';


-- -----------------------------------------------------
-- Table `irkpo_events`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`roles` (
                                                      `roleID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор роли',
                                                      `roleName` VARCHAR(50) NOT NULL COMMENT 'Наименование роли (студент, преподаватель, администратор)',
    PRIMARY KEY (`roleID`),
    UNIQUE INDEX `roleName_UNIQUE` (`roleName` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица ролей пользователей';


-- -----------------------------------------------------
-- Table `irkpo_events`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`users` (
                                                      `userID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор пользователя',
                                                      `firstName` VARCHAR(50) NOT NULL COMMENT 'Имя пользователя',
    `lastName` VARCHAR(50) NOT NULL COMMENT 'Фамилия пользователя',
    `middleName` VARCHAR(50) NULL COMMENT 'Отчество пользователя (при наличии)',
    `email` VARCHAR(100) NOT NULL COMMENT 'Электронная почта пользователя',
    `password` VARCHAR(255) NOT NULL COMMENT 'Пароль пользователя',
    `isActive` TINYINT NOT NULL DEFAULT 1 COMMENT 'Статус пользователя. По умолчанию 1 (true)',
    `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата создания записи',
    `roles_roleID` INT NULL COMMENT 'Связь ролей (статуса) с пользователями',
    `groups_groupID` INT NULL COMMENT 'Связь учебных групп с пользователями',
    PRIMARY KEY (`userID`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_users_roles1_idx` (`roles_roleID` ASC) VISIBLE,
    INDEX `fk_users_groups1_idx` (`groups_groupID` ASC) VISIBLE,
    CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`roles_roleID`)
    REFERENCES `irkpo_events`.`roles` (`roleID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`groups_groupID`)
    REFERENCES `irkpo_events`.`groups` (`groupID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица всех  пользователей';


-- -----------------------------------------------------
-- Table `irkpo_events`.`eventTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`eventTypes` (
                                                           `eventTypeID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор типа мероприятия',
                                                           `eventType` VARCHAR(100) NOT NULL COMMENT 'Тип мероприятия',
    PRIMARY KEY (`eventTypeID`),
    UNIQUE INDEX `eventType_UNIQUE` (`eventType` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица типов мероприятий';


-- -----------------------------------------------------
-- Table `irkpo_events`.`eventStatuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`eventStatuses` (
                                                              `eventStatusID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор статуса мероприятия',
                                                              `eventStatus` VARCHAR(50) NOT NULL DEFAULT 'planed' COMMENT 'Статус мероприятия. По умолчанию - \'planed\'',
  PRIMARY KEY (`eventStatusID`),
  UNIQUE INDEX `eventStatus_UNIQUE` (`eventStatus` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Таблица статусов мероприятий';


-- -----------------------------------------------------
-- Table `irkpo_events`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`events` (
                                                       `eventID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор мероприятия',
                                                       `title` VARCHAR(100) NOT NULL COMMENT 'Название мероприятия',
    `description` TEXT NULL COMMENT 'Описание, всё мероприятие',
    `startDateTime` DATETIME NOT NULL COMMENT 'Начало мероприятия',
    `endDateTime` DATETIME NOT NULL COMMENT 'Конец мероприятия',
    `location` VARCHAR(255) NOT NULL COMMENT 'Место проведения мероприятия',
    `budget` DECIMAL(10,2) NULL COMMENT 'Общий бюджет мероприятия',
    `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Когда запись создана',
    `eventTypes_eventTypeID` INT NULL COMMENT 'Связь тип мероприятия - мероприятие',
    `eventStatuses_eventStatusID` INT NULL COMMENT 'Связь статус мероприятия - мероприятие',
    `users_OrganizerID` INT NULL COMMENT 'Связь организатора мероприятия - мероприятие',
    `faculties_facultyID` INT NULL COMMENT 'Связь Отделений с его мероприятия',
    PRIMARY KEY (`eventID`),
    INDEX `fk_events_eventTypes1_idx` (`eventTypes_eventTypeID` ASC) VISIBLE,
    INDEX `fk_events_eventStatuses1_idx` (`eventStatuses_eventStatusID` ASC) VISIBLE,
    INDEX `fk_users_organizerID1_idx` (`users_OrganizerID` ASC) VISIBLE,
    INDEX `fk_events_faculties1_idx` (`faculties_facultyID` ASC) VISIBLE,
    CONSTRAINT `fk_events_eventTypes1`
    FOREIGN KEY (`eventTypes_eventTypeID`)
    REFERENCES `irkpo_events`.`eventTypes` (`eventTypeID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_events_eventStatuses1`
    FOREIGN KEY (`eventStatuses_eventStatusID`)
    REFERENCES `irkpo_events`.`eventStatuses` (`eventStatusID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_users_organizerID1`
    FOREIGN KEY (`users_OrganizerID`)
    REFERENCES `irkpo_events`.`users` (`userID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_events_faculties1`
    FOREIGN KEY (`faculties_facultyID`)
    REFERENCES `irkpo_events`.`faculties` (`facultyID`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица мероприятий';


-- -----------------------------------------------------
-- Table `irkpo_events`.`eventRegistrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`eventRegistrations` (
                                                                   `registrationID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор регистрации пользователей на мероприятие',
                                                                   `registrationDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата регистрации на мероприятие',
    `statusEventRegistration` VARCHAR(50) NOT NULL DEFAULT 'active' COMMENT 'Статус регистрации. По умолчанию \'active\'',
  `events_eventID` INT NULL COMMENT 'Связь мероприятий с зарегистрированными мероприятиями',
  `users_userID` INT NULL COMMENT 'Связь пользователей с зарегистрированными мероприятиями',
  PRIMARY KEY (`registrationID`),
  INDEX `eventRegistrations_eventID1_idx` (`events_eventID` ASC) INVISIBLE,
  INDEX `eventRegistrations_users_usersID1_idx` (`users_userID` ASC) VISIBLE,
  UNIQUE INDEX `unique_user_event` (`events_eventID` ASC, `users_userID` ASC) COMMENT 'Индекс для недопущения повторной регистрации на мероприятие' VISIBLE,
  CONSTRAINT `fk_eventRegistrations_events_eventID1`
    FOREIGN KEY (`events_eventID`)
    REFERENCES `irkpo_events`.`events` (`eventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eventRegistrations_users_usersID1`
    FOREIGN KEY (`users_userID`)
    REFERENCES `irkpo_events`.`users` (`userID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Таблица регистраций на мероприятия';


-- -----------------------------------------------------
-- Table `irkpo_events`.`expenseCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`expenseCategories` (
                                                                  `expenseCategoryID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор категории расходов',
                                                                  `categoryName` VARCHAR(50) NOT NULL COMMENT 'Категория расходов',
    PRIMARY KEY (`expenseCategoryID`),
    UNIQUE INDEX `categoryName_UNIQUE` (`categoryName` ASC) VISIBLE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица категорий расходов';


-- -----------------------------------------------------
-- Table `irkpo_events`.`eventExpenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`eventExpenses` (
                                                              `ExpenseID` INT NOT NULL AUTO_INCREMENT COMMENT 'Униклаьный идентификатор расходов',
                                                              `itemName` VARCHAR(100) NOT NULL COMMENT 'Наименование расхода',
    `amount` DECIMAL(10,2) NOT NULL COMMENT 'Итоговая стоимость расхода',
    `purchaseDate` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата покупки товара',
    `expenseCategories_expenseCategoryID` INT NULL COMMENT 'Связь типов расходов с расходами',
    `users_purchasedBy` INT NULL COMMENT 'Связь пользователей (тот кто купил) с расходами',
    `events_eventID` INT NULL COMMENT 'Связь с мероприятиями и его расходами',
    PRIMARY KEY (`ExpenseID`),
    INDEX `fk_eventExpenses_expenseCategories1_idx` (`expenseCategories_expenseCategoryID` ASC) INVISIBLE,
    INDEX `fk_eventExpenses_users` (`users_purchasedBy` ASC) VISIBLE,
    INDEX `fk_eventExpenses_events` (`events_eventID` ASC) VISIBLE,
    CONSTRAINT `fk_eventExpenses_expenseCategories1`
    FOREIGN KEY (`expenseCategories_expenseCategoryID`)
    REFERENCES `irkpo_events`.`expenseCategories` (`expenseCategoryID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_eventExpenses_users_userID1`
    FOREIGN KEY (`users_purchasedBy`)
    REFERENCES `irkpo_events`.`users` (`userID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
    CONSTRAINT `fk_eventExpenses_events_eventID1`
    FOREIGN KEY (`events_eventID`)
    REFERENCES `irkpo_events`.`events` (`eventID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица всех расходов на каждое мероприятие';


-- -----------------------------------------------------
-- Table `irkpo_events`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `irkpo_events`.`feedbacks` (
                                                          `feedbackID` INT NOT NULL AUTO_INCREMENT COMMENT 'Уникальный идентификатор отзыва',
                                                          `comment` TEXT NULL COMMENT 'Текст отзыва',
                                                          `rating` INT NOT NULL COMMENT 'Рейтинг пользователя (от 1 до 5)',
                                                          `createdAt` DATETIME NULL DEFAULT CURRENT_TIMESTAMP() COMMENT 'Дата создания записи',
    `registrationID` INT NULL COMMENT 'Связь регистрации на мероприятие и его отзывов',
    PRIMARY KEY (`feedbackID`),
    INDEX `fk_eventRegistrationID1_idx` (`registrationID` ASC) VISIBLE,
    CONSTRAINT `fk_eventRegistrationID1`
    FOREIGN KEY (`registrationID`)
    REFERENCES `irkpo_events`.`eventRegistrations` (`registrationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `chk_rating_range` CHECK (`rating` >= 1 AND `rating` <= 5)
    )
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'Таблица отзывов';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
